/*
 * File: app/view/DetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TreatLocations.view.DetailPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.detailpanel',

    requires: [
        'Ext.Map',
        'Ext.tab.Bar',
        'Ext.XTemplate',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        activeItem: 1,
        items: [
            {
                xtype: 'map',
                title: 'Map',
                id: 'detailMap'
            },
            {
                xtype: 'container',
                title: 'Contact',
                id: 'contact',
                items: [
                    {
                        xtype: 'container',
                        id: 'info',
                        padding: 10,
                        tpl: [
                            
                            '<h2>{name}</h2>',
                            '<div class="info">',
                            '    {address1}<br/>',
                           
                            '</div>'
                        ],
                        layout: 'hbox',
                        items: [
                           
                            {
                                xtype: 'component',
                                id: 'data',
                                padding: 10,
                                tpl: [
                                    '<h2>{name}</h2>',
                                    '<div class="info">',
                                    '    {address1}<br/>',
                                    '    <img src="{rating_img_url_small}"/>',
                                    '</div>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                           
                            {
                                xtype: 'spacer',
                                width: 57
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'moreButton',
                                width: 100,
                                text: 'More'
                            }
                        ]
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'top',
            ui: 'light',
            layout: {
                type: 'hbox',
                pack: 'center'
            }
        }
    }

});