/*
 * File: app/view/DetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TreatLocations.view.DetailPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.detailpanel',

    requires: [
        'Ext.Map',
		'TreatLocations.store.BusinessStore'
        'Ext.tab.Bar',
        'Ext.XTemplate',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        activeItem: 1,
        items: [
            {
                xtype: 'map',
                title: 'Map',
                id: 'detailMap'
            },
            {
                xtype: 'container',
                title: 'Contact',
                id: 'contact',
                items: [
                    {
                        xtype: 'container',
                        id: 'data',
                        padding: 10,
                        itemTpl: [
						 Ext.create('Ext.XTemplate',{
	                        getDistance: function(uuid){
	                           dist=TreatLocations.globals.distanceDictionary;
	                           return dist[uuid];
                            ],
                    store: {xclass : 'TreatLocations.store.BusinessStore'}    
                        },
						
                   tabBar: {
                   docked: 'top',
                   ui: 'light',
                   layout: {
                   type: 'hbox',
                   pack: 'center'
            }
        }
    }

});