/*
 * File: app/view/SearchByDoctor.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
 Ext.define('TreatLocations.view.SearchByDoctor',{
	extend: 'Ext.Panel',
	alias: 'widget.searchbydoctor',
	xtype: 'searchbydoctor',
	config: {
		layout:{
		    type  : 'vbox',
		    align : 'center'
		},
		items: [{
			xtype: 'fieldset',
			title: 'Current Location',
			layout: 'vbox',
			items: [{
				xtype: 'textfield',
				name: 'latitude',
				label: 'Latitude'
			},
			{
				xtype: 'textfield',
				name: 'longitude',
				label: 'Longitude'
			}]
		}]
	}
});

