/*
 * File: app/view/SignUp.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
 Ext.define('TreatLocations.view.SignUp', {
    extend: 'Ext.tab.Panel',

    requires: [
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Map',
        'Ext.Toolbar',
        'Ext.field.Url',
        'Ext.field.Email',
        'Ext.Button'
    ],

    config: {
        layout: {
            type: 'card',
            animation: 'pop'
        },

         items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'emailfield',
                                width: 315,
                                label: 'Email',
                                placeHolder: 'sushantlakhina29@gmail.com'
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'textfield',
                                width: 316,
                                label: 'Address'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        width: 317,
                        text: 'Submit'
                    }
                ]
            },
            {
                xtype: 'textfield',
                label: 'Field'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Doctors May Sign Up'
            }
        ]
    }

});