/*
 * File: app/model/Business.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

xt.define( 'TreatLocations.model.Business', {
	extend: 'Ext.data.Model',
	config: {
	  fields: [
	    'uuid',
	    'display',
	    'distance',
	    'name',
	    'description',
	    'address1',
	    'address2',
	    'cityVillage',
	    'stateProvince',
	    'country',
	    'postalCode',
	    'latitude',
	    'longitude',
	    'countryDistrict',
	    'address3',
	    'address4',
	    'address5',
	    'address6',
	    'tags',
	    'parentLocation',
	    'childLocations',
	    'retired',
	    'auditInfo',
	    'attributes',
	    'links',
	    'resourceVersion'
	  ],
	  proxy: {
		  type: 'ajax',
		  url: '/openmrs-standalone/ws/rest/v1/location?v=full',
		  reader: {
			  type: 'json',
			  rootProperty: 'results'
		  },
		  listeners: {
		    metachange: function( proxy, data, eOpts ){console.log(data+'inside proxy listeners');}
		  }
	  },
	autoload: true
	}
});