/*
 * File: app/controller/Business.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TreatLocations.controller.Business', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            dataList: '#dataList',
            listCard: '#listCard',
            mainNav: 'mainnav',
            detailCard: 'detailpanel'
        },

        control: {
            "#dataList": {
                itemtap: 'onListItemTap'
            },
            
            "detailpanel > map": {
                activate: 'onMapActivate'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var map,
            info,
            details;

        if (record) {
            details = Ext.create('TreatLOcations.view.DetailPanel', {
                title: 'Details'
            });

            // set the map
            map = details.child('#detailMap');
            map._record = record;

            // set the info
            info = details.child('#contact').child('#info');
            
            info.child('#data').setData(record.data);

            this.getMainNav().push(details);
        }
    },

   
    onMapActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        var map = newActiveItem,
            record = map._record,
            lat = record.get('latitude'),
            lng = record.get('longitude'),
            centerMap = Ext.Function.createDelayed(function() {
                map.setMapOptions({
                    zoom: 18
                });
                map.setMapCenter({
                    latitude: lat,
                    longitude: lng
                });
            }, 250),
            geocoder, loc;

        if (lat && lng) {
            centerMap();
        } else {
            geocoder = this._geocoder || (this._geocoder = new google.maps.Geocoder());
            geocoder.geocode(
            {address: [
                record.get('address1'),
                record.get('address2'),
                record.get('address3'),
                record.get('city'),
                record.get('postalCode'),
                record.get('stateProvince')
            ].join(', ')},
            function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    loc = results[0].geometry.location;
                    lat = loc.lat();
                    lng = loc.lng();
                    record.set('latitude', lat);
                    record.set('longitude', lng);
                    centerMap();
                } else {
                    Ext.Msg.alert("Could not find location: " + status);
                }
            }
            );
        }

    },

    launch: function() {

        var me = this;

        

      
        Ext.Viewport.setMasked({ xtype: 'loadmask', message: 'Loading...' });
        me.getLocation(function (location) {

            me.getBusinesses(location, function (store) {

                
                me.getDataList().setStore(store);

                Ext.Viewport.setMasked(false);

            });

        });

    },

    getLocation: function(callback) {
        if (navigator && navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                callback(position);
            }, function(error) {
                // give a warning for error
            });
        }
    },

    getBusinesses: function(location, callback) {

        var store = Ext.data.StoreManager.lookup('BusinessStore'),
            url = 'http://localhost:8084/openmrs-standalone/ws/rest/v1/location' ;
        store.getProxy().setUrl(url);
        store.load(function() {
            callback(store);
        });

    }

});